trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  - task: NodeTool@0
    inputs:
      versionSpec: '20'
    displayName: Install Node.js
  - script: |
      git config --global user.name "${GH_NAME}"
      git config --global user.email "${GH_EMAIL}"
      git checkout -b main
      echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      yarn install
      GIT_USER="${GH_NAME}" yarn deploy
    env:
      GH_NAME: $(GH_NAME)
      GH_EMAIL: $(GH_EMAIL)
      GH_TOKEN: $(GH_TOKEN)
      ALGOLIA_APP_ID: $(ALGOLIA_APP_ID)
      ALGOLIA_API_KEY: $(ALGOLIA_API_KEY)
      ALGOLIA_INDEX_NAME: $(ALGOLIA_INDEX_NAME)
    displayName: Install and build
  - task: ado-discord-webhook@1
    inputs:
        channelId: '1053584023970136076'
        webhookKey: 'lg4HDINSzABhevGkyFbdG0paNAzLJYqa3x_dkgLBYde342W6uHDsJR8m33vaTIu7vrnH'
        messageType: 'content'
        content: 'Azure Pipelines build finished: $(Agent.JobStatus). ```Repository: $(Build.Repository.Name) | Build number: $(Build.BuildNumber) | Message: $(Build.SourceVersionMessage)```'